apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: backup
spec:
  selector:
    matchLabels:
      app: backup
  replicas: 1
  template:
    metadata:
      labels:
        app: backup
    spec:
      containers:
      - name: backup
        image: seungwooklee/backup:v1.1
        ports: 
          - containerPort: 7777
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: R1_HOST
          value: mysql
        - name: R1_PORT
          value: '3306'
        - name: R2_HOST
          value: mysql2
        - name: R2_PORT
          value: '3306'
        - name: MINIO_HOST
          value: minio:9000
        - name: MINIO_USER
          value: rootuser
        - name: MINIO_PASSWD
          value: rootpass123
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: '6379'
        