apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql2
spec:
  selector:
    matchLabels:
      app: mysql2
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql2
    spec:
      containers:
      - image: mysql:5.6
        name: mysql2
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql2
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql2
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim2